import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'
import Navbar from '@/components/navbar'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { ModeToggle } from '@/components/theme/mode-toggle'

export const metadata: Metadata = {
  title: 'Shreyas P',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={GeistSans.className}>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <div className='px-8 md:w-2/5 mx-auto text-lg'>
              <Navbar />
              {children}
            </div>
            <div className='fixed bottom-7 right-7'>
              <ModeToggle />
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
